//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sutcift
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Gelirler
    {
        public int GelİD { get; set; }
        public string Tarihi { get; set; }
        public string Tür { get; set; }
        public Nullable<int> Tutar { get; set; }
    }
}
