//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sutcift
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_inek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_inek()
        {
            this.Tb_ırkı = new HashSet<Tb_ırkı>();
            this.Tb_Sağlık = new HashSet<Tb_Sağlık>();
            this.Tb_Sut = new HashSet<Tb_Sut>();
        }
    
        public int İnİD { get; set; }
        public string İnekAdı { get; set; }
        public string Kulak_etiketi { get; set; }
        public string Renk { get; set; }
        public string Irkı { get; set; }
        public string Doğum_tarihi { get; set; }
        public Nullable<int> Yaş { get; set; }
        public Nullable<int> Doğum_ağırlığı { get; set; }
        public string Otlak { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ırkı> Tb_ırkı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Sağlık> Tb_Sağlık { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Sut> Tb_Sut { get; set; }
    }
}
