//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sutcift
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Satışı
    {
        public int SatİD { get; set; }
        public string Tarihi { get; set; }
        public int Fiyat { get; set; }
        public string MüşteriAdı { get; set; }
        public string MüşteriNo { get; set; }
        public int Miktar { get; set; }
        public string Toplam { get; set; }
    }
}
