//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sutcift
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Sağlık
    {
        public int RapİD { get; set; }
        public Nullable<int> İnekİD { get; set; }
        public string İnekAdı { get; set; }
        public string Durum { get; set; }
        public string Teşhis { get; set; }
        public string Tedavi { get; set; }
        public Nullable<int> Maliyeti { get; set; }
        public string VeterinAdı { get; set; }
    
        public virtual Tb_inek Tb_inek { get; set; }
    }
}
