//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sutcift
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Sut
    {
        public int SütİD { get; set; }
        public Nullable<int> İnekİD { get; set; }
        public string İnekAdı { get; set; }
        public Nullable<int> SabahSütü { get; set; }
        public Nullable<int> ÖğlenSütü { get; set; }
        public Nullable<int> AkşamSütü { get; set; }
        public Nullable<int> Toplam { get; set; }
        public string Tarihi { get; set; }
    
        public virtual Tb_inek Tb_inek { get; set; }
    }
}
