//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sutcift
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ırkı
    {
        public int ırİD { get; set; }
        public string kızgınlıktar { get; set; }
        public string cinstar { get; set; }
        public Nullable<int> inekİD { get; set; }
        public string inekAdı { get; set; }
        public string gebeliktar { get; set; }
        public string beklenentar { get; set; }
        public string doğumtar { get; set; }
        public Nullable<int> inekyaş { get; set; }
        public string uyaılar { get; set; }
    
        public virtual Tb_inek Tb_inek { get; set; }
    }
}
